# Generated by Django 2.0.2 on 2018-02-25 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180220_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdocumentpackage',
            name='design_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.DesignDocument'),
        ),
    ]
