# Generated by Django 2.0.2 on 2018-02-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180225_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdocumentimage',
            name='design_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.DesignDocument'),
        ),
        migrations.AlterField(
            model_name='designdocumentpackage',
            name='design_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DesignDocument'),
        ),
    ]
